[project]
name = "smashtop"
version = "0.1.0"
description = "Smashtop application"
requires-python = ">=3.10"
dependencies = [
    "keyboard==0.13.5",
    "pillow==12.1.0",
    "pygame>=2.6.1",
]

[tool.uv]
managed = true
